### PR TITLE
add: TSBigIntKeyword (BigInt) support

### PR DESCRIPTION
**Pull request by chr33s**

### CODE REVIEW

**Comment by leonardfactory** [comment]
Hi @chr33s, is this released in TS stable? Maybe we need to update the TS version in the package since the `tsc --noEmit` is throwing an error here (see the CI log)

**Comment by chr33s** [comment]
@leonardfactory its included in TypeScript 3.2[1], although targeting esnext

[0] https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html

**Comment by leonardfactory** [comment]
Going to use #28 instead in order to fix TSC typings
Thank you @chr33s and sorry for the long delay.

**Comment by chr33s** [comment]
@leonardfactory all good, thanks for maintaining the package.

**Pull request closed without merging**
