### PR TITLE
🐛 Use cloneDeep to keep reference linked

### LINKED ISSUE #37: Reference Error "X is not defined"
@leonardfactory @wtho 
When working with Nestjs and aws sdk, any injections of AWS sdk are not being tranformed properly. I think the issue is somewhere in [here](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/master/src/metadata/serializeType.ts#L83). when the condition expression fails for `typeof Type === 'undefined' ? Object : Type` it falls back to default type which for example is `AWS.S3` and later js has no idea of how to resolve `AWS`.

reproduction of the issue is [here](https://github.com/whimzyLive/babel-ts-imports-removed-repro). The original issue was filed in babel repro as [#12150](https://github.com/babel/babel/issues/12150)

Happy to work on this, but will need more guidence on what actually needs to be fixed.

### PR DESCRIPTION
**Pull request by wtho**
In serializeTypeReferenceNode, by using `cloneDeep` instead of
`clone`, the cloned references are all affected by future
transformations like renames.

I looked at the tests, but I am a bit clueless about a test plan, as I do not know how to check the difference between `clone` and `cloneDeep`. Any ideas, @leonardfactory?

fixes #37

### CODE REVIEW

**Comment by leonardfactory** [comment]
I'm looking at the differences between `clone` and `cloneDeep`. Ironically, I tried to use just `reference` but weird issues appeared, so I'm curious about `cloneDeep` behaviour. This step is critical since all references are retained with `path.scope.crawl()` that looks on reference nodes. I'll update you asap.

**Comment by leonardfactory** [comment]
Uhm easier than I thought. The problem with `clone` is that it work correctly for first level node references (i.e. `S3`) since node is just an `Identifier`. When writing `AWS.S3` you get an AST member expression, containing another identifier inside. Since this last node is not cloned, I suppose references are lost and crawling doesn't work. Awesome job my friend!

In order to test this, you can just add type def to a parameter with a member expression, like `param30: AWS.S3` (i.e. in already existing [type-serialization/code.js](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/master/test/__fixtures__/type-serialization/code.js) test file) and check the output.js file to be sure the transformation has been applied (i.e. `Reflect.defineMetadata(..., __awsSdk.S3`)). `output.js` is generated on jest run, like a normal snapshot, just override it if it seems correct to you, I'll check it again. Thank you 😄 

PS: add something like `import AWS from 'aws'` in order to let the transformation happen, I'm writing it since I'm not sure it is clear that all imports are absolutely fake and needed only as AST mocks in the `code.js` source. Furthermore don't mind the extension, it's a TS file 👍

**Comment by wtho** [comment]
I think I tried the `AWS.S3` expression, but the `AWS` remained untouched by the transformer, so the differenc could not be observed, but I can give it another try.

**Comment by leonardfactory** [comment]
Probably `AWS` remains untouched due to missing `@babel/plugin-transform-modules-commonjs` plugin. 
What I am thinking about is:
- Add another configuration test case, like `modules.spec.ts` sibling to [`plugin.spec.ts`](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/master/test/plugin.spec.ts)
- Add `@babel/plugin-transform-modules-commonjs` in the plugins section, changing the directory to `__modules__` instead of `__fixtures__`. 
- Install devdep (`npm i --save-dev @babel/plugin-transform-modules-commonjs`)
- Create a new test file in `__modules__/member-expression/code.js` and put simple class with the `AWS.S3` decorator (like original issue):

```ts
import AWS from 'aws-sdk';

@Injectable()
export class SomeService {
 constructor(
    @Inject('aws.s3') private s3client: AWS.S3,
  ) {}
}
```

Then AWS should be rewritten and decorator should match signature. Let me know if you've got other questions I missed

**Comment by wtho** [comment]
Ok, got you! I'll try it out later.

**Comment by wtho** [comment]
Done! Thanks for the test instructions!

You would do me a great favor by adding a label called `hacktoberfest-accepted` to this PR to mark it as a useful contribution, as I am currently spending some extra free time to participate in hacktoberfest 😉 I also understand if you do not want to mess with *weird* labels though.

**Comment by leonardfactory** [comment]
Awesome! About the label, I hope the color is spooky enough 😄 
However I've found another issue that I'm worried about: the output is `typeof __awsSdk.default.S3`, and this would surely cause issues if `__awsSdk` is undefined or `__awsSdk.default` is undefined. Not sure if this could be possible anyway, given ES imports, but I'm thinking about issues with namespaces.
Well, let us merge this and see if there are edge cases, this should not break actual code since it wasn't handled at all.

PPS: I've seen `@babel/plugin-transform-modules-commonjs` is not in the deps (`package.json` didn't change); are you sure you added it to dev deps? i.e. `yarn add --dev @babel/plugin-transform-modules-commonjs`

**Comment by wtho** [comment]
Thanks for the label!

No, I didn't add `@babel/plugin-transform-modules-commonjs` to the deps, but the test looked good with the transformed `_awsSdk`, and the test passed, so I thought it might already be included.
Should I add it?

**Comment by leonardfactory** [comment]
Maybe it's already in another preset, if you can add it on the fly it would be great (so it is explicit), elseway I'll just add it before releasing 👍

**Comment by wtho** [comment]
Added the dependency :+1:

**Comment by leonardfactory** [comment]
perfect, lgtm!

**Pull request merged**
